### ISSUE TITLE
support for OS X Mavericks | Yosemite

### ISSUE THREAD

**Issue by nyotis** [hmazhar/physbam_public#2]
Months before I got the issue at https://github.com/andrewseidl/physbam-cmake/issues/1
I tried to get in touch with the developers, no reply. You know if the project is actively supported? It doesn't seem so

**Comment by hmazhar** [comment]
I went through the code and made changes so that clang (6.0) is supported. This means that the latest version of Xcode should work as well. Haven't tried using the clang compiled version with an external project yet, there is a chance that there will be linking issues.
